name: Deploy to Dev Environment

on:
  push:
    branches: [develop]
    paths:
      - 'server/**'
      - 'web/**'
      - 'shared/**'
      - 'docker-compose.prod.yml'
      - 'docker-compose.dev.yml'
      - '.github/workflows/deploy-dev.yml'

permissions:
  contents: read
  packages: write

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      server-changed: ${{ steps.changes.outputs.server }}
      web-changed: ${{ steps.changes.outputs.web }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Detect changes
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            server:
              - 'server/**'
              - 'shared/**'
              - 'docker-compose.prod.yml'
              - 'docker-compose.dev.yml'
            web:
              - 'web/**'
              - 'shared/**'
              - 'docker-compose.prod.yml'
              - 'docker-compose.dev.yml'

  build-and-push-server:
    needs: detect-changes
    if: needs.detect-changes.outputs.server-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push server image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./server/Dockerfile
          push: true
          tags: |
            ghcr.io/daniserrano7/telechat-server:dev-latest
            ghcr.io/daniserrano7/telechat-server:dev-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-and-push-web:
    needs: detect-changes
    if: needs.detect-changes.outputs.web-changed == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Build and push web image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./web/Dockerfile
          push: true
          tags: |
            ghcr.io/daniserrano7/telechat-web:dev-latest
            ghcr.io/daniserrano7/telechat-web:dev-${{ github.sha }}
          build-args: |
            VITE_API_URL=${{ secrets.VITE_API_URL }}
            VITE_WS_URL=${{ secrets.VITE_WS_URL }}
            VITE_PORT=${{ secrets.VITE_PORT }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

  deploy:
    needs: [detect-changes, build-and-push-server, build-and-push-web]
    if: always() && (needs.build-and-push-server.result == 'success' || needs.build-and-push-web.result == 'success' || (needs.build-and-push-server.result == 'skipped' && needs.build-and-push-web.result == 'skipped' && (needs.detect-changes.outputs.server-changed == 'true' || needs.detect-changes.outputs.web-changed == 'true')))
    runs-on: ubuntu-latest
    environment: DEV
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Create deployment directory on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            mkdir -p /opt/telegram-clone-dev
            cd /opt/telegram-clone-dev
            
      - name: Copy docker-compose to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          source: "docker-compose.dev.yml,.docker/"
          target: "/opt/telegram-clone-dev/"
          
      - name: Deploy to Dev Environment
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USERNAME }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd /opt/telegram-clone-dev
            
            # Export environment variables for development
            # No longer needed since we hardcoded the username
            export DATABASE_URL="${{ secrets.DATABASE_URL }}"
            export JWT_SECRET="${{ secrets.JWT_SECRET }}"
            export ALLOWED_ORIGINS="${{ secrets.ALLOWED_ORIGINS }}"
            export VITE_API_URL="${{ secrets.VITE_API_URL }}"
            export VITE_WS_URL="${{ secrets.VITE_WS_URL }}"
            export VITE_PORT="${{ secrets.VITE_PORT }}"
            export DB_USER="${{ secrets.DB_USER }}"
            export DB_NAME="${{ secrets.DB_NAME }}"
            export DB_PASSWORD="${{ secrets.DB_PASSWORD }}"
            export PORT="5000"
            
            # Login to GitHub Container Registry on VPS
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
            
            # Pull latest dev images
            docker-compose -f docker-compose.dev.yml pull
            
            # Start services
            docker-compose -f docker-compose.dev.yml up -d
            
            # Clean up old images
            docker image prune -f
            
            # Show running containers
            docker-compose -f docker-compose.dev.yml ps